/*
	Class Name Extraction Tool
	By GhostriderDbD
	For Arma 3
	
	Lists weapons that should excluded from the output for the script.
	
	
	All the code and information provided here is provided under an Attribution Non-Commercial ShareAlike 4.0 Commons License.

	http://creativecommons.org/licenses/by-nc-sa/4.0/		
*/

/*

	Include any classnames you wish to exclude from the lists generated by the tool by adding them to _airBase using the formating below.
	The list below includes the default Arma 3 UAVs of APEX.
	
		"B_UAV_01_F",
		"O_UAV_01_F",
		"I_UAV_01_F",
		"UAV_02_base_F",
		"UAV_02_CAS_base_F",
		"B_UAV_02_F",
		"O_UAV_02_F",
		"I_UAV_02_F",
		"B_UAV_02_CAS_F",
		"O_UAV_02_CAS_F",
		"I_UAV_02_CAS_F"
	*/
_airBase = [

	
];
