/*
	Class Name Extraction Tool
	By GhostriderDbD
	For Arma 3
	
	Lists weapons that should excluded from the output for the script.
	
	
	All the code and information provided here is provided under an Attribution Non-Commercial ShareAlike 4.0 Commons License.

	http://creativecommons.org/licenses/by-nc-sa/4.0/		
*/
/*

	Include any classnames you wish to exclude from the lists generated by the tool using the formating below.
	The list below includes certains default Arma 3 glasses as of APEX.
	
	
		"G_Sport_Red",
		"G_Tactical_Black",
		"G_Aviator",
		"G_Lady_Mirror",
		"G_Lady_Dark",
		"G_Lady_Red",
		"G_Lady_Blue",
		"G_Diving",
		"G_B_Diving",
		"G_O_Diving",
		"G_I_Diving"
	*/

_baseWearables = [

];
