/*
	Class Name Extraction Tool
	By GhostriderDbD
	For Arma 3
	
	Lists weapons that should excluded from the output for the script.
	
	
	All the code and information provided here is provided under an Attribution Non-Commercial ShareAlike 4.0 Commons License.

	http://creativecommons.org/licenses/by-nc-sa/4.0/		
*/

/*

	Include any classnames you wish to exclude from the lists generated by the tool by adding them to _knownWeapons using the formating below.
	The list below includes the default Arma 3 MX series of assaault rifles as of APEX.
	
	"arifle_MX_Base_F",
	"arifle_MXC_F",
	"arifle_MX_F",
	"arifle_MXM_F",
	"arifle_MXC_Black_F",
	"arifle_MX_Black_F",
	"arifle_MXM_Black_F"
	*/
_knownWeapons = [


	
];
