/*
	Class Name Extraction Tool
	By GhostriderDbD
	For Arma 3
	
	Lists weapons that should excluded from the output for the script.
	
	
	All the code and information provided here is provided under an Attribution Non-Commercial ShareAlike 4.0 Commons License.

	http://creativecommons.org/licenses/by-nc-sa/4.0/		
*/
/*

	Include any classnames you wish to exclude from the lists generated by the tool using the formating below.
	The list below includes certains default Arma 3 glasses as of APEX.
	
	
		"G_Sport_Red",
		"G_Tactical_Black",
		"G_Aviator",
		"G_Lady_Mirror",
		"G_Lady_Dark",
		"G_Lady_Red",
		"G_Lady_Blue",
		"G_Diving",
		"G_B_Diving",
		"G_O_Diving",
		"G_I_Diving"
	*/

_excludedWearables = [
// Uniforms 

"Exile_Uniform_BambiOverall",
"Exile_Uniform_ExileCustoms",
"Exile_Uniform_Wetsuit_AAF",
"Exile_Uniform_Wetsuit_CSAT",
"Exile_Uniform_Wetsuit_NATO",
"Exile_Uniform_Woodland",


// Headgear 

"Exile_Cap_Exile",
"Exile_Headgear_SafetyHelmet",
"Exile_Headgear_SantaHat",


// Vests 

"Exile_Vest_Rebreather_AAF",
"Exile_Vest_Rebreather_CSAT",
"Exile_Vest_Rebreather_NATO",
"Exile_Vest_Snow",


// Backpacks 



// Glasses 

"Exile_Glasses_Diving_AAF",
"Exile_Glasses_Diving_CSAT",
"Exile_Glasses_Diving_NATO"
];
