/*
	Class Name Extraction Tool
	By GhostriderDbD
	For Arma 3
	
	Lists weapons that should excluded from the output for the script.
	
	
	All the code and information provided here is provided under an Attribution Non-Commercial ShareAlike 4.0 Commons License.

	http://creativecommons.org/licenses/by-nc-sa/4.0/		
*/

/*

	Include any classnames you wish to exclude from the lists generated by the tool by adding them to _knownWeapons using the formating below.
	The list below includes the default Arma 3 MX series of assaault rifles as of APEX.
	
	"arifle_MX_Base_F",
	"arifle_MXC_F",
	"arifle_MX_F",
	"arifle_MXM_F",
	"arifle_MXC_Black_F",
	"arifle_MX_Black_F",
	"arifle_MXM_Black_F"
	*/
_excludedWeapons = [


/*

        Exile Trader Item Lists

*/

// Assault Rifles  

"Exile_Weapon_AK107",
"Exile_Weapon_AK74",
"Exile_Weapon_AK47",
"Exile_Weapon_AKM",
"Exile_Weapon_AKS",
"Exile_Weapon_AKS_Gold",
"exile_arifle_M16A4",
"Exile_Weapon_M16A4",
"exile_arifle_M16A2",
"Exile_Weapon_M16A2",
"exile_arifle_M4",
"Exile_Weapon_M4",
"Exile_Weapon_DMR",
"Exile_Weapon_ksvk",
"Exile_Weapon_LeeEnfield",
"Exile_Weapon_CZ550",
"Exile_Weapon_SVD",
"Exile_Weapon_SVDCamo",
"Exile_Weapon_VSSVintorez",
"Exile_Weapon_RPK",
"Exile_Weapon_M1014",


// Assault Rifles with GL 

"Exile_Weapon_AK107_GL",
"Exile_Weapon_AK74_GL",


// LMGs 

"Exile_Weapon_PK",
"Exile_Weapon_PKP",


//  SMGs  



// Snipers  

"exile_weapons_m107",
"Exile_Weapon_m107",


// DMRs  



// Launchers  



// Handguns  

"Exile_Weapon_Colt1911",
"Exile_Weapon_Makarov",
"Exile_Weapon_Taurus",
"Exile_Weapon_TaurusGold",
"exile_rifle_SA61",
"Exile_Weapon_SA61",


// Shotguns  



// Throwables  

"Exile_Melee_Axe",
"Exile_Melee_Shovel",
"Exile_Melee_SledgeHammer",


// Magazines  

"Exile_Magazine_Swing",
"Exile_Magazine_Boing",
"Exile_Magazine_Swoosh",
"Exile_Magazine_30Rnd_545x39_AK",
"Exile_Magazine_30Rnd_545x39_AK_Green",
"Exile_Magazine_30Rnd_545x39_AK_Red",
"Exile_Magazine_30Rnd_545x39_AK_White",
"Exile_Magazine_30Rnd_545x39_AK_Yellow",
"Exile_Magazine_30Rnd_762x39_AK",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag_green",
"30Rnd_556x45_Stanag_red",
"30Rnd_556x45_Stanag_Tracer_Red",
"30Rnd_556x45_Stanag_Tracer_Green",
"30Rnd_556x45_Stanag_Tracer_Yellow",
"Exile_Magazine_20Rnd_762x51_DMR",
"Exile_Magazine_20Rnd_762x51_DMR_Yellow",
"Exile_Magazine_20Rnd_762x51_DMR_Red",
"Exile_Magazine_20Rnd_762x51_DMR_Green",
"Exile_Magazine_5Rnd_127x108_APDS_KSVK",
"Exile_Magazine_5Rnd_127x108_KSVK",
"Exile_Magazine_5Rnd_127x108_KSVK_Bullet_Cam_Mag",
"Exile_Magazine_5Rnd_127x108_APDS_KSVK_Bullet_Cam_Mag",
"10Rnd_127x99_m107",
"Exile_Magazine_10Rnd_127x99_m107",
"Exile_Magazine_10Rnd_127x99_m107_Bullet_Cam_Mag",
"Exile_Magazine_10Rnd_303",
"Exile_Magazine_5Rnd_22LR",
"Exile_Magazine_10Rnd_762x54",
"Exile_Magazine_10Rnd_9x39",
"Exile_Magazine_20Rnd_9x39",
"Exile_Magazine_45Rnd_545x39_RPK_Green",
"Exile_Magazine_75Rnd_545x39_RPK_Green",
"Exile_Magazine_100Rnd_762x54_PK_Green",
"Exile_Magazine_7Rnd_45ACP",
"Exile_Magazine_8Rnd_9x18",
"Exile_Magazine_6Rnd_45ACP",
"10Rnd_765x17ball",
"20Rnd_765x17ball",
"Exile_Magazine_10Rnd_765x17_SA61",
"Exile_Magazine_20Rnd_765x17_SA61",
"Exile_Magazine_8Rnd_74Slug",
"Exile_Magazine_8Rnd_74Pellets",


// Optics  

"optic_Nightstalker",
"optic_tws",
"optic_tws_mg",
"optic_NVS",
"optic_DMS",
"optic_LRPS",
"optic_ams",
"optic_AMS_snd",
"optic_AMS_khk",
"optic_KHS_blk",
"optic_KHS_tan",
"optic_KHS_hex",
"optic_KHS_old",
"optic_SOS",
"optic_MRCO",
"optic_Arco",
"optic_aco",
"optic_ACO_grn",
"optic_aco_smg",
"optic_ACO_grn_smg",
"optic_hamr",
"optic_Holosight",
"optic_Holosight_smg",
"optic_Hamr_khk_F",
"optic_SOS_khk_F",
"optic_Arco_ghex_F",
"optic_Arco_blk_F",
"optic_DMS_ghex_F",
"optic_ERCO_blk_F",
"optic_ERCO_khk_F",
"optic_ERCO_snd_F",
"optic_LRPS_ghex_F",
"optic_LRPS_tna_F",
"optic_Holosight_blk_F",
"optic_Holosight_khk_F",
"optic_Holosight_smg_blk_F",
"optic_Holosight_smg_khk_F",
"optic_Hamr",
"optic_AMS",


// Muzzles  

"muzzle_snds_M",
"muzzle_snds_L",


// Pointers  

"acc_flashlight",
"acc_pointer_IR",


// Underbarrel  

"bipod_01_F_snd",
"bipod_01_F_blk",
"bipod_01_F_mtp",
"bipod_01_F_khk",
"bipod_02_F_blk",
"bipod_02_F_tan",
"bipod_02_F_hex",
"bipod_03_F_blk",
"bipod_03_F_oli"
	
];
