How To Use This Tool.

1) Start Arma 3 with any mods for which you wish to extract class names.
2) Start the Eden Editor.
3) Open the testConfig.Altis mission.

You are now ready to generate the class names. The tools copy these to the clipboard. 
All you need to do to generate a list of classnames:
  - is select the tool for the category for which you want to generate lists of class names, 
  - Alt-Tab out of Arma, 
  - and paste the contents of the clipboard into a text editor such as notepad ++.
  
For each category (e.g., uniforms, weapons, vehicles) the tools will generate three types of lists:

- a list of class names in quotes, useful for putting together lists of items that are available through certain traders.
- pricelists formated in either Epoch or Exile format (which, of course need prices adjusted).
- a list suitable for addition to either the loot tables in Epoch or the loot table compiler in Exile.

You can determine which format of price list will be generated by changing GRG_mod in init.sqf.

Settings:

GRG_mod: set to "Epoch" or "Exile"
GRG_Root: Use this to process only class names with a certain name such as "CUP" or "RHS".
GRG_addIttemsMissingFromPricelistOnly (true/false).
When true, the tool will search for a price for that class name in either CfgPricing (epoch) or CfgExileArsenal (Exile). 
	The idea behind this is to list only those items that you have not already added to traders. this should be handy when dealing with mod updates.
	To use this requires a bit of extra setup.
	- add a description.ext to the mission folder.
	- add an #include to the description.ext so as to include CfgPricing.hpp or your exile_config.hpp and be sure any included files these use are also in the mission folder in the appropriate subfolder or commented out.
	- The tool will check for a price for each item and if no price is found add that item to the output.

Credits:
	The original algorithm for extracting weapons class names is derived from one posted by KiloSwiss on EpochMod although it has more recently been updated:
	https://epochmod.com/forum/topic/32239-howto-get-available-weapons-mod-independent/
	
License
	All the code and information provided here is provided under an Attribution Non-Commercial ShareAlike 4.0 Commons License.

	http://creativecommons.org/licenses/by-nc-sa/4.0/		
	
	
	There is no charge to use these tools.
	You may modify any of the tools as you like.
	Please give credit to me and those listed above if redistributing modified code.
	
